# Filepath: /srv/exatorent/docker-compose.yml
#
# A docker conatiner to act as a torrent seeded
#
# run docker-compose up -d to start the container

version: "3.7"
services:
    vpn:
      container_name: vpn
      image: qmcgaw/gluetun
      restart: always
      cap_add:
        - NET_ADMIN
      environment:
        - VPN_SERVICE_PROVIDER=protonvpn
        - OPENVPN_USER=<openvpn username>
        - OPENVPN_PASSWORD=<openvpn pass>
        - SERVER_COUNTRIES=Netherlands
        - FREE_ONLY=on

      # network_mode: host
      networks:
        - mynetwork
      ports:
        - 5000:5000
        - 42069:42069

    exatorrent:
      image: ghcr.io/varbhat/exatorrent:latest
      container_name: exatorrent
      restart: always

      mem_limit: 256mb

      network_mode: service:vpn
      depends_on:
        - vpn

      # ports:
      #   - 5000:5000
      #   - 42069:42069
      # volumes:
      #     - ./data:/exa/exadir

networks:
  mynetwork:                                 
    external: true
